version: "3.8"
services:
  backend:
    build: .
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    container_name: text_completion_backend
    restart: always
    env_file: 
      - .env  # Load environment variables from .env file
    environment:
      AZURE_OPENAI_ENDPOINT: "${AZURE_OPENAI_ENDPOINT}"      # Explicitly pass environment variables
      AZURE_OPENAI_DEPLOYMENT: "${AZURE_OPENAI_DEPLOYMENT}"
      AZURE_SUBSCRIPTION_KEY: "${AZURE_SUBSCRIPTION_KEY}"
      AZURE_API_VERSION: "${AZURE_API_VERSION}"
    networks:
      - text_completion

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: text_completion_frontend
    restart: always
    networks:
      - text_completion

networks:
  text_completion: